// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zglvtspmrihotbfbjtvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbHZ0c3Btcmlob3RiZmJqdHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODY0MzksImV4cCI6MjA3MjY2MjQzOX0.eI9SjUJp8IktKbi-ZoJsMYTGnmpvAG8Wzpec7l0RbO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});